### ISSUE TITLE
请问一下，我的blog通过域名访问有些资源加载不到要如何解决？

### ISSUE THREAD

**Issue by SongZihuan** [BigCoke233/adams#5]
通过ipv4地址进行访问一切正常，标题栏隔壁的github图标等显示是正常的。  
但是通过域名访问，github图标就会变成方块，资源似乎没加载出来。  
我使用的是宝塔搭建的  
服务器是CentOS8.0
域名是：(http://www.songzh.com)[http://www.songzh.com]  
ipv4地址是(http://47.56.87.77/)[http://47.56.87.77/]  
谢谢

**Comment by BigCoke233** [comment]
检查 typecho 后台设置，站点地址里填写的网址是否和域名一致

**Comment by SongZihuan** [comment]
谢谢，我在后台设置改成我现在的域名后就可以了。
